#!/usr/bin/env python
"""
Create new episode folder.
Episode brief and all content are generated by workflows — this script only creates the folder.
"""

import sys
import re
from pathlib import Path


def get_next_episode_id(episodes_dir: Path, prefix: str = "PP") -> str:
    """Find highest existing episode number and return next ID."""
    pattern = re.compile(rf"^{prefix}_(\d+)$")
    max_num = 0

    if episodes_dir.exists():
        for folder in episodes_dir.iterdir():
            if folder.is_dir():
                match = pattern.match(folder.name)
                if match:
                    num = int(match.group(1))
                    max_num = max(max_num, num)

    return f"{prefix}_{max_num + 1:04d}"


def create_episode(episode_id: str = None, prefix: str = "PP"):
    """
    Create episode folder (empty).

    Args:
        episode_id: Optional. If not provided, auto-generates next ID.
        prefix: Episode ID prefix (default: PP for Pet Psychology)
    """
    episodes_dir = Path("episodes")

    # Auto-generate ID if not provided
    if not episode_id:
        episode_id = get_next_episode_id(episodes_dir, prefix)
        print(f"Auto-generated Episode ID: {episode_id}")

    # Create folder
    episode_dir = episodes_dir / episode_id
    episode_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n✅ Episode folder ready: {episode_dir}")
    print(f"   Next step: /gen_outline → /gen_episode_brief")

    return episode_id


def main():
    """Main entry point."""
    episode_id = None
    prefix = "PP"

    # Parse arguments
    for arg in sys.argv[1:]:
        if arg.startswith("--prefix="):
            prefix = arg.split("=")[1]
        elif not arg.startswith("--"):
            episode_id = arg

    if "--help" in sys.argv or "-h" in sys.argv:
        print("Usage: python create_episode.py [EPISODE_ID] [--prefix=PP]")
        print("\nExamples:")
        print("  python create_episode.py              # Auto-generate next ID")
        print("  python create_episode.py PP_0001      # Create specific episode")
        print("  python create_episode.py --prefix=PP  # Use different prefix")
        sys.exit(0)

    create_episode(episode_id, prefix)


if __name__ == "__main__":
    main()
